vm_name: ubuntu24-vm
box: ubuntu/noble64
hostname: ubuntu.local
private_ip: 192.168.56.20

forwarded_port:
  guest: 80
  host: 8080

public_network: false           # or true

memory: 1024
cpus: 1
gui: false
