# Default box used if not specified per VM
default_box: ubuntu/jammy64

vms:
  master:
    hostname: jenkins
    ip: 192.168.56.11
    memory: 4096
    cpus: 2
    ports:
      - { guest: 8080, host: 8080 }
    synced_folder:
      host: ./shared
      guest: /vagrant_data


  agent1:
    hostname: sonar
    ip: 192.168.56.12
    memory: 4096
    cpus: 2
    ports:
      - { guest: 9000, host: 9000 }

  agent2:
    hostname: nexus
    ip: 192.168.56.13
    memory: 4096
    cpus: 2
    ports:
      - { guest: 8081, host: 8081 }




# agent1-sonar → Jenkins agent + SonarQube
# agent2-nexus → Jenkins agent + Nexus
